### ISSUE TITLE
Custom Language Files?

### ISSUE THREAD

**Issue by MixingOnBeat** [marttiphpbb/phpbb-ext-inserttemplatecode#1]
I was wondering if you have a tip for those that want to add words to the language files--especially for those that have multiple languages installed.  

I was hoping to use something like this, this way I don't need to edit the main lang files each time I update the main site files or translated lang files.

**Comment by eeemarv** [comment]
I guess the way to go is to copy the language files in order to maintain your own version. See https://phpbb.com (or ask there on the community forum).
This extension is just a little framework to insert your own template code. So that's got nothing to do with your question.

**Comment by marttiphpbb** [comment]
I guess the way to go is to copy the language files in order to maintain your own version. See https://phpbb.com (or ask there on the community forum).
This extension is just a little framework to insert your own template code. So that's got nothing to do with your question.
